config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations", invitations: "users/invitations", omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/profile' => 'users#show', as: :show_profile
    get 'users/profile/edit' => 'registrations#edit_profile', as: :edit_profile
    put 'users/profile/update' => 'registrations#update_profile', as: :update_profile
   end
  resources :listings
  resources :transactions, only: [:new, :create]
  resources :messages, only: [:create]
  resources :crews, only: [:create]
  resources :pictures, only: [:destroy]

  resources :signatures, only: [:show, :create] do
    collection do
      post 'callbacks'
    end
  end

  get  'bookingrequests/'  => 'booking_requests#index'
  get  'bookingrequest/'   => 'booking_requests#show'
  post 'bookingrequests/accept' => 'booking_requests#accept'
  post 'bookingrequests/reject' => 'booking_requests#reject'

  post 'listings/orbit'
  post 'listings/unorbit'
  post 'listings/update_date'
  post 'listings/request' => 'listings#booking_request'
  get  'crews/leave' => 'crews#leave_crew'
  patch 'crews/add_user'

  get '/requests/accept' => 'crew_requests#accept_request'
  get '/requests/reject' => 'crew_requests#reject_request'

  get 'search/results'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/crews' => 'dashboard#crews'
  get 'dashboard/myproperties' => 'dashboard#properties'
  get 'dashboard/following' => 'dashboard#following'
  get 'dashboard/requests' => 'dashboard#requests'

  get 'tos'      => 'pages#tos'
  get 'privacy'  => 'pages#privacy'
  get 'equal'    => 'pages#equal'

  root to: "pages#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!

  def index
    @user = current_user
    @my_properties = current_user.owned_listings
    @crew_requests = current_user.crew_requests
    @followed_listings = current_user.orbits
    @my_crews = current_user.crews
    if current_user.landlord
      redirect_to dashboard_myproperties_path
    else
      redirect_to dashboard_crews_path
    end
  end

  def properties
    @user = current_user
    @listings = current_user.owned_listings
  end

  def following
    @orbits = current_user.orbits
  end

  def requests
    @request = current_user.crew_requests
  end

  def crews
    @crews = current_user.crews
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_listing.html.erb
<%= image_tag listing.images.first, width: 800, height: 533, class: "img-responsive", alt: "" %>
<%= listing.price %></span>
<%= link_to listing.title, edit_listing_path(id: listing) %>
<%= listing.city%>, <%= listing.state %>

app/views/dashboard/bookingrequests.html.erb
<div id="page-content">

        <div class="container page">
            <div class="row">
            <!-- sidebar -->
            <div class="col-md-3 col-sm-2">
                <section id="sidebar">
                    <header><h3>Dashboard</h3></header>
                    <aside>
                      <ul class="sidebar-navigation">
                        <% if current_user.regular_user %>
                          <li class="active"><%= link_to dashboard_path do %>
                            <i class="fa fa-user"></i><span>My Crews</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_requests_path do %>
                            <i class="fa fa-home"></i><span>Crew Requests</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_following_path do %>
                            <i class="fa fa-home"></i><span>Followed Listings</span></a>
                            <% end %>
                          </li>
                        <% end %>
                        <% if current_user.landlord %>
                          <li><%= link_to dashboard_myproperties_path do %>
                            <i class="fa fa-home"></i><span>My Properties</span></a>
                            <% end %>
                          </li>
                          <li class="active"><%= link_to bookingrequests_path do %>
                            <i class="fa fa-home"></i><span>Booking Requests</span></a>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </aside>
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
                <!-- My Properties -->
                <div class="col-md-9 col-sm-10">
                    <section id="my-properties">
                        <header><h1>My Crews</h1></header>
                        <div class="my-properties">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Property</th>
                                        <th></th>
                                        <th>Dates</th>
                                        <th>Users</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                      <% @requests.each do |request| %>
                                      <% listing = request.listing %>
                                      <% crew = request.crew %>
                                        <tr>
                                            <td class="image">
                                                <a href="property-detail.html"><img alt="" src="assets/img/properties/property-04.jpg"></a>
                                            </td>
                                            <td><div class="inner">
                                                <%= link_to listing do %>
                                                <h2 style="text-align: left;"><%= listing.title %></h2>
                                                <% end %>
                                                <figure><%= listing.full_address %></figure>
                                                <div class="tag price">$ <%= listing.price %></div>
                                            </div>
                                            </td>
                                            <td>
                                              <%= crew.start_date.strftime("%B %Y") %></br>
                                              <%= "#{pluralize(crew.lease_length, "Month")}" %>
                                            </td>
                                            <td>
                                              <% crew.users.each do |other_user| %>
                                                  <%= link_to "#{other_user.username}", show_profile_path(id: other_user) %></br>
                                              <% end %>
                                              <% other_requested_users = [] %>
                                              <% crew.crew_requests.each do |other_request| %>
                                                  <% if other_request.user != current_user %>
                                                      <% other_requested_users << other_request.user %>
                                                  <% end %>
                                              <% end %>
                                            </td>
                                            <td class="actions">
                                                <%= link_to bookingrequest_path(id: request), class: "edit" do %>
                                                  <i class="fa fa-pencil"></i>See Request
                                                <% end %>
                                            </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /.my-properties -->
                    </section><!-- /#my-properties -->
                </div><!-- /.col-md-9 -->
                <!-- end My Properties -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <!-- end Page Content -->

app/views/dashboard/crews.html.erb
<div id="page-content">

        <div class="container page">
            <div class="row">
            <!-- sidebar -->
            <div class="col-md-3 col-sm-2">
                <section id="sidebar">
                    <header><h3>Dashboard</h3></header>
                    <aside>
                      <ul class="sidebar-navigation">
                        <% if current_user.regular_user %>
                          <li class="active"><%= link_to dashboard_path do %>
                            <i class="fa fa-users"></i><span>My Crews</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_requests_path do %>
                            <i class="fa fa-exclamation-circle"></i><span>Crew Requests</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_following_path do %>
                            <i class="fa fa-home"></i><span>Followed Listings</span></a>
                            <% end %>
                          </li>
                        <% end %>
                        <% if current_user.landlord %>
                          <li><%= link_to dashboard_myproperties_path do %>
                            <i class="fa fa-home"></i><span>My Properties</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to bookingrequests_path do %>
                            <i class="fa fa-home"></i><span>Booking Requests</span></a>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </aside>
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
                <!-- My Properties -->
                <div class="col-md-9 col-sm-10">
                    <section id="my-properties">
                        <header><h1>My Crews</h1></header>
                        <div class="my-properties">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Property</th>
                                        <th></th>
                                        <th>Dates</th>
                                        <th>Users</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                      <% @crews.each do |crew| %>
                                      <% listing = crew.listing %>
                                        <tr>
                                            <td class="image">
                                                <a href="property-detail.html"><img alt="" src="assets/img/properties/property-04.jpg"></a>
                                            </td>
                                            <td><div class="inner">
                                                <%= link_to listing do %>
                                                <h2 style="text-align: left;"><%= listing.title %></h2>
                                                <% end %>
                                                <figure><%= listing.full_address %></figure>
                                                <div class="tag price">$ <%= listing.price %></div>
                                            </div>
                                            </td>
                                            <td>
                                              <%= crew.start_date.strftime("%B %Y") %></br>
                                              <%= "#{pluralize(crew.lease_length, "Month")}" %>
                                            </td>
                                            <td>
                                              <% crew.users.each do |other_user| %>
                                                  <%= link_to "#{other_user.username}", show_profile_path(id: other_user) %></br>
                                              <% end %>
                                              <% other_requested_users = [] %>
                                              <% crew.crew_requests.each do |other_request| %>
                                                  <% if other_request.user != current_user %>
                                                      <% other_requested_users << other_request.user %>
                                                  <% end %>
                                              <% end %>
                                              <% if other_requested_users.any? %>
                                                Pending:</br>
                                                <% other_requested_users.each do |other_requested_user| %>
                                                    <%= link_to "#{other_requested_user.username}", show_profile_path(id: other_requested_user) %></br>
                                                <% end %>
                                              <% end %>
                                            </td>
                                            <td class="actions">
                                                <%= link_to crews_leave_path(crew: crew), class: "edit" do %>
                                                  <i class="fa fa-times"></i>Leave Crew
                                                <% end %>
                                            </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /.my-properties -->
                    </section><!-- /#my-properties -->
                </div><!-- /.col-md-9 -->
                <!-- end My Properties -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <!-- end Page Content -->

app/views/dashboard/following.html.erb
<div id="page-content">

        <div class="container page">
            <div class="row">
            <!-- sidebar -->
            <div class="col-md-3 col-sm-2">
                <section id="sidebar">
                    <header><h3>Dashboard</h3></header>
                    <aside>
                      <ul class="sidebar-navigation">
                        <% if current_user.regular_user %>
                          <li><%= link_to dashboard_path do %>
                            <i class="fa fa-users"></i><span>My Crews</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_requests_path do %>
                            <i class="fa fa-exclamation-circle"></i><span>Crew Requests</span></a>
                            <% end %>
                          </li>
                          <li class="active"><%= link_to dashboard_following_path do %>
                            <i class="fa fa-home"></i><span>Followed Listings</span></a>
                            <% end %>
                          </li>
                        <% end %>
                        <% if current_user.landlord %>
                          <li><%= link_to dashboard_myproperties_path do %>
                            <i class="fa fa-home"></i><span>My Properties</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to bookingrequests_path do %>
                            <i class="fa fa-home"></i><span>Booking Requests</span></a>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </aside>
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
                <!-- My Properties -->
                <div class="col-md-9 col-sm-10">
                    <section id="my-properties">
                        <header><h1>Followed Listings</h1></header>
                        <div class="my-properties">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Property</th>
                                        <th></th>
                                        <th>Move in</th>
                                        <th>Lease Length</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                  <% @orbits.each do |orbit| %>
                                  <% listing = orbit.listing %>
                                    <tr>
                                        <td class="image">
                                              <%= link_to listing do %>
                                              <%= image_tag listing.pictures.first.image.url(:medium) if listing.pictures.any? %>
                                              <% end %>
                                        </td>
                                        <td><div class="inner">
                                            <%= link_to listing do %>
                                            <h2 style="text-align: left;"><%= listing.title %></h2>
                                            <% end %>
                                            <figure><%= listing.full_address %></figure>
                                            <div class="tag price">$ <%= listing.price %></div>
                                        </div>
                                        </td>
                                        <td><%= orbit.start_date.strftime("%B %Y") %></td>
                                        <td><%= orbit.lease_length %></td>
                                        <td class="actions">
                                          <%= link_to listing_path(listing.id), class: "edit" do %>
                                            <i class="fa fa-pencil"></i>Edit
                                          <% end %>
                                        </td>
                                    </tr>
                                  <% end %>

                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                            <!-- Pagination -->
                        </div><!-- /.my-properties -->
                    </section><!-- /#my-properties -->
                </div><!-- /.col-md-9 -->
                <!-- end My Properties -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <!-- end Page Content -->

app/views/dashboard/properties.html.erb
<div id="page-content">

        <div class="container page">
            <div class="row">
            <!-- sidebar -->
            <div class="col-md-3 col-sm-2">
                <section id="sidebar">
                    <header><h3>Dashboard</h3></header>
                    <aside>
                        <ul class="sidebar-navigation">
                          <% if current_user.regular_user %>
                            <li><%= link_to dashboard_path do %>
                              <i class="fa fa-users"></i><span>My Crews</span></a>
                              <% end %>
                            </li>
                            <li><%= link_to dashboard_requests_path do %>
                              <i class="fa fa-exclamation-circle"></i><span>Crew Requests</span></a>
                              <% end %>
                            </li>
                            <li><%= link_to dashboard_following_path do %>
                              <i class="fa fa-home"></i><span>Followed Listings</span></a>
                              <% end %>
                            </li>
                          <% end %>
                          <% if current_user.landlord %>
                            <li class="active"><%= link_to dashboard_myproperties_path do %>
                              <i class="fa fa-home"></i><span>My Properties</span></a>
                              <% end %>
                            </li>
                            <li><%= link_to bookingrequests_path do %>
                              <i class="fa fa-exclamation-circle"></i><span>Booking Requests</span></a>
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                    </aside>
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
                <!-- My Properties -->
                <div class="col-md-9 col-sm-10">
                    <section id="my-properties">
                        <header><h1>My Properties</h1></header>
                        <div class="my-properties">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                      <tr>
                                          <th>Property</th>
                                          <th></th>
                                          <th>Date Added</th>
                                          <th>Followers</th>
                                          <th>Actions</th>
                                      </tr>
                                      </thead>
                                      <tbody>
                                    <% @listings.each do |listing| %>
                                      <tr>
                                          <td class="image">
                                              <a href="property-detail.html"><img alt="" src="assets/img/properties/property-04.jpg"></a>
                                          </td>
                                          <td><div class="inner">
                                              <%= link_to listing do %>
                                                <h2 style="text-align: left;"><%= listing.title %></h2>
                                              <% end %>
                                              <figure><%= listing.full_address %></figure>
                                              <div class="tag price">$ <%= listing.price %></div>
                                          </div>
                                          </td>
                                          <td><%= listing.created_at.to_date.to_formatted_s(:long) %></td>
                                          <td><%= listing.users.count %></td>
                                          <td class="actions">
                                              <%= link_to edit_listing_path(id: listing), class: "edit" do %>
                                                <i class="fa fa-pencil"></i>Edit
                                              <% end %>
                                              <%= button_to listing, controller: "listings", action: "destroy", method: "delete", style: "background-color: rgba(0,0,0,0); border:none;" do %>
                                                <i class="delete">Delete
                                              <% end %>
                                          </td>
                                      </tr>
                                    <% end %>
                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /.my-properties -->
                    </section><!-- /#my-properties -->
                </div><!-- /.col-md-9 -->
                <!-- end My Properties -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <!-- end Page Content -->

app/views/dashboard/requests.html.erb
<div id="page-content">

        <div class="container page">
            <div class="row">
            <!-- sidebar -->
            <div class="col-md-3 col-sm-2">
                <section id="sidebar">
                    <header><h3>Dashboard</h3></header>
                    <aside>
                      <ul class="sidebar-navigation">
                        <% if current_user.regular_user %>
                          <li><%= link_to dashboard_path do %>
                            <i class="fa fa-users"></i><span>My Crews</span></a>
                            <% end %>
                          </li>
                          <li class="active"><%= link_to dashboard_requests_path do %>
                            <i class="fa fa-exclamation-circle"></i><span>Crew Requests</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to dashboard_following_path do %>
                            <i class="fa fa-home"></i><span>Followed Listings</span></a>
                            <% end %>
                          </li>
                        <% end %>
                        <% if current_user.landlord %>
                          <li><%= link_to dashboard_myproperties_path do %>
                            <i class="fa fa-home"></i><span>My Properties</span></a>
                            <% end %>
                          </li>
                          <li><%= link_to bookingrequests_path do %>
                            <i class="fa fa-exclamation-circle"></i><span>Booking Requests</span></a>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </aside>
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
                <!-- My Properties -->
                <div class="col-md-9 col-sm-10">
                    <section id="my-properties">
                        <header><h1>Crew Requests</h1></header>
                        <div class="my-properties">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Property</th>
                                        <th></th>
                                        <th>Dates</th>
                                        <th>Users</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                  <% @request.each do |request| %>
                                  <% crew = request.crew %>
                                  <% listing = crew.listing %>
                                    <tr>
                                        <td class="image">
                                            <a href="property-detail.html"><img alt="" src="assets/img/properties/property-04.jpg"></a>
                                        </td>
                                        <td><div class="inner">
                                            <%= link_to listing do %>
                                            <h2 style="text-align: left;"><%= listing.title %></h2>
                                            <% end %>
                                            <figure><%= listing.full_address %></figure>
                                            <div class="tag price">$ <%= listing.price %></div>
                                        </div>
                                        </td>
                                        <td>
                                          <%= crew.start_date.strftime("%B %Y") %></br>
                                          <%= "#{pluralize(crew.lease_length, "Month")}" %>
                                        </td>
                                        <td>
                                          <% crew.users.each do |other_user| %>
                                              <%= link_to "#{other_user.username}", show_profile_path(id: other_user) %></br>
                                          <% end %>
                                          <% other_requested_users = [] %>
                                          <% crew.crew_requests.each do |other_request| %>
                                              <% if other_request.user != current_user %>
                                                  other_requested_users << other_request.user
                                              <% end %>
                                          <% end %>
                                          <% if other_requested_users.any? %>
                                            Pending:</br>
                                            <% other_requested_users.each do |other_requested_user| %>
                                                <%= link_to "#{other_requested_user.username}", show_profile_path(id: other_requested_user) %></br>
                                            <% end %>
                                          <% end %>
                                        </td>
                                        <td class="actions">
                                            <%= link_to requests_accept_path(id: request), class: "edit" do %>
                                              <i class="fa fa-check"></i>Accept
                                            <% end %>
                                            </br></br>
                                            <%= link_to requests_reject_path(id: request), class: "edit" do %>
                                              <i class="fa fa-times"></i> Reject
                                            <% end %>
                                        </td>
                                    </tr>
                                    <% end %>
                                    </tbody>
                                </table>
                            </div><!-- /.table-responsive -->
                        </div><!-- /.my-properties -->
                    </section><!-- /#my-properties -->
                </div><!-- /.col-md-9 -->
                <!-- end My Properties -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <!-- end Page Content -->