config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations", invitations: "users/invitations", omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/profile' => 'users#show', as: :show_profile
    get 'users/profile/edit' => 'registrations#edit_profile', as: :edit_profile
    put 'users/profile/update' => 'registrations#update_profile', as: :update_profile
   end
  resources :listings
  resources :transactions, only: [:new, :create]
  resources :messages, only: [:create]
  resources :crews, only: [:create]
  resources :pictures, only: [:destroy]

  resources :signatures, only: [:show, :create] do
    collection do
      post 'callbacks'
    end
  end

  get  'bookingrequests/'  => 'booking_requests#index'
  get  'bookingrequest/'   => 'booking_requests#show'
  post 'bookingrequests/accept' => 'booking_requests#accept'
  post 'bookingrequests/reject' => 'booking_requests#reject'

  post 'listings/orbit'
  post 'listings/unorbit'
  post 'listings/update_date'
  post 'listings/request' => 'listings#booking_request'
  get  'crews/leave' => 'crews#leave_crew'
  patch 'crews/add_user'

  get '/requests/accept' => 'crew_requests#accept_request'
  get '/requests/reject' => 'crew_requests#reject_request'

  get 'search/results'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/crews' => 'dashboard#crews'
  get 'dashboard/myproperties' => 'dashboard#properties'
  get 'dashboard/following' => 'dashboard#following'
  get 'dashboard/requests' => 'dashboard#requests'

  get 'tos'      => 'pages#tos'
  get 'privacy'  => 'pages#privacy'
  get 'equal'    => 'pages#equal'

  root to: "pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_email_as_username, :check_if_landlord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  attr_writer :invitation_instructions
  validates :email, :presence => true, :email => true, if: :regular_user

  has_attached_file :avatar, styles: { medium: "300x300>", square: '200x200#', thumb: "100x100>" },
      default_url: "missing-user.jpg",
      url: "/system/:id/:style/:hash.:extension",
      hash_secret: '3dc4ae38d8884935e31bde595c06001d153982069650c1c4e326a47c69e723ee970e7cb0ef334b1fdf32e1e8d7e7cd31a92abaa828c349360b81293d47af2d41'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :crew_requests
  has_many :user_crew_memberships
  has_many :crews, through: :user_crew_memberships

  has_many :orbits
  has_many :listings, through: :orbits

  has_many :crew_approval_requests
  has_many :owned_listings, class_name: "Listing", foreign_key: "owner_id"

  belongs_to :invited_booking_request, class_name: "BookingRequest", foreign_key: "invited_booking_request_id"
  belongs_to :invited_crew_request, class_name: "CrewRequest", foreign_key: "invited_crew_request_id"

  def set_email_as_username
    self.username = self.email
  end

  def check_if_landlord
    self.landlord = true if self.regular_user == false
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split(' ').first   # assuming the user model has a name
      user.last_name = auth.info.name.split(' ').last
      user.username = "facebook:#{auth.uid}"
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def deliver_invitation
   if @invitation_instructions.present?
     ::Devise.mailer.send(@invitation_instructions, self).deliver
   else
     super
   end
  end

  def self.invite_landlord!(attributes={}, invited_by=nil)
   self.invite!(attributes, invited_by) do |invitable|
     invitable.invitation_instructions = :landlord_invitation_instructions
   end
  end

  def self.invite_friend!(attributes={}, invited_by=nil)
   self.invite!(attributes, invited_by) do |invitable|
     invitable.invitation_instructions = :friend_invitation_instructions
   end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  private
    def accept_resource
      resource = resource_class.accept_invitation!(update_resource_params)
      if resource.invited_booking_request
        resource.invited_booking_request.listing.update(owner: resource)
        resource.update(landlord: true)
      elsif resource.invited_crew_request
        crew_request = resource.invited_crew_request
        crew = crew_request.crew
        orbit = Orbit.create(listing: crew.listing, crew: crew, user: resource, start_date: crew.start_date, end_date: crew.end_date, has_crew: true)
        crew.users << resource
        crew_request.destroy
      end
      resource
    end

    def update_resource_params
      params.require(resource_name).permit(
        :invitation_token,
        :password,
        :password_confirmation,
        :first_name,
        :last_name,
        :email
      )
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/invitations/edit.html.erb
<!-- Page Content -->
<div id="page-content">
    <div class="container page">
        <header><h1><%= t 'devise.invitations.edit.header' %></h1></header>
        <div class="row">
          </br></br></br>
            <div class="col-md-5 col-sm-6 col-md-offset-4 col-sm-offset-3">
                <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:class => "user_sign", :method => :put } do |f| %>
                  <%= devise_error_messages! %>
                  <%= f.hidden_field :invitation_token %>
                    <div class="form-group">
                        <%= f.label :first_name %>
                        <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
                    </div><!-- /.form-group -->
                    <div class="form-group">
                        <%= f.label :last_name %>
                        <%= f.text_field :last_name, class: "form-control" %>
                    </div><!-- /.form-group -->
                    <div class="form-group">
                        <%= f.label :password %>
                        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
                    </div><!-- /.form-group -->
                    <div class="form-group">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
                    </div><!-- /.form-group -->
                    <div class="form-group clearfix">
                        <%= f.submit t("devise.invitations.edit.submit_button"), class: "btn btn-default", style: "margin-top: 5px; width: 100%;" %>
                    </div><!-- /.form-group -->
                <% end %>
                <br>
                <div class="center"><%= render "users/shared/links" %></div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</div>
<!-- end Page Content -->

app/views/users/invitations/new.html.erb
<!-- Page Content -->
<div id="page-content">
    <div class="container page">
        <header><h1><%= t "devise.invitations.new.header" %></h1></header>
        <div class="row">
          </br></br></br>
            <div class="col-md-5 col-sm-6 col-md-offset-4 col-sm-offset-3">
              <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:class => "user_sign", :method => :post} do |f| %>
                  <%= devise_error_messages! %>
                  <% resource.class.invite_key_fields.each do |field| -%>
                    <div class="form-group">
                        <%= f.label field %>
                        <%= f.text_field field, class: "form-control" %>
                    </div><!-- /.form-group -->
                  <% end -%>
                    <div class="form-group clearfix">
                        <%= f.submit t("devise.invitations.new.submit_button"), class: "btn btn-default", style: "margin-top: 5px; width: 100%;" %>
                    </div><!-- /.form-group -->
                <% end %>
                <br>
                <div class="center"><%= render "users/shared/links" %></div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</div>
<!-- end Page Content -->